### ISSUE TITLE
Uncaught (in promise): TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided. TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.  

### ISSUE THREAD

**Issue by VenimirPetkov** [FabianGosebrink/angular-face-recognition-api#2]
When I try to take a picture throws this error in the console : Uncaught (in promise): TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.

**Comment by FabianGosebrink** [comment]
Should be fixed now :)
